<?php
//array de nomes
$nome=array("Eduarda","Mariana","alice","manuela","livia","lorena","isadora","fernanda","cecilia","bruna","luana","juliana","sophia","yasmin","amanda","leticia","valentina","camila","lara","helena","isabela","laura","beatriz","maria","ana","julia","manuela","vitoria","aline","sara","luiza","luna","gabriela","giovanna","jessica","bianca","melissa","carolina","ester","vanessa","heloisa","rafaela","nicole","milena","isabella","lais","anaclara","eloá","barbara","emily","sabrina","raquel","mariaclara","thais","catarina","patricia","daniela","brenda","adriana","marina","eduarda","lavinia","isis","debora","priscila","alana","caroline","marialuiza","hadassa","raissa","natalia","emilly","isabel","luisa","alicia","joana","ayla","sarah","giovana","anabeatriz","anacarolina","analuiza","marcela","aurora","jaqueline","talita","luciana","maite","anajulia","clara","diana","stephanie","evelyn","rayane","ingrid","anapaula","cristina","liz","elisa","jennifer","andressa","pietra","maya","agata","geovana","alessandra","marcia","mayara","sandra","ohana","erica","janaina","claúdia","antonella","nina","kelly","graziela","laiane","tatiana","mirela","carla","adriele","gisele","elaine","taina","zoe","samara","iris","tais","gabrielle","agatha","viviane","paula","michele","pamela","olivia","poliana","flavia","simone","monica","karen","nathalia","fatima","eliane","andreia","thamires","lia","mariajulia","perola","lis","joyce","cintia","louise","karina","emanuelly","victoria","esther","mariafernanda","tainara","jade","laisa","kiara","micaela","roberta","ellen","fabiana","nayara","giulia","lorraine","rosana","maisa","eloah","marta","safira","aisha","sonia","paloma","clarice","isabele","lilian","isabelly","manuella","regina","gabriel","eva","analaura","francisca","paola","emmanuelle","mirian","ariane","valeria","alexia","amira","veronica","agnes","Monique","Danielle","Alexandra","Lúcia","Natalie","MariaLuísa","Geovanna","Jenifer","Rosângela","Elisângela","Denise","Rayssa","Estela","Michelle","Stefany","MariaAlice","Karine","Dayane","Elizabeth","Mariah","Sophie","Iara","MariaVitória","Antônia","Silvana","Betina","Inês","Laila","Eliana","Sheila","Dandara","Ludmila"."Marlene","Ângela","Sueli","Vânia","Cibele","Kamila","Solange","Lana","Thalia","Mara","Edna","Kaylane","Carol","Ketlyn","Tatiane","Isabelle","Carina","Cristiane","Eloísa","Maia","Bella","Hannah","AnaLuísa","Noemi","Melina","Morgana","Lídia","Rute","Malu","Karoline","Margarida","Raiane","Marisa","Marília","Iasmin","Rosa","Daiane","Sílvia","Anita","Andréa","MariaCecília","Kátia","Tânia","Vivian","Jamile","Natasha","Elis","Célia","Mel","Keila","Yasmim","Teresa","Suelen","Daniele","QuerenHapuque","Samantha",",","Luara","Cristiana","Leonor","Maíra","Vera","Hellen","Alisson","Andreza","Thamires","Joice","Elena","Anne
M","arjorie","Diane","Nicolly","Stella","Luma","Kimberly","Yara","Suzana","Susana","Lidiane","Madalena","Cássia","Angélica","Suellen","Késia","MariaHelena","Luzia","Kauane","Camille","AnaLívia","Liliane","Eliza","Jacqueline","Manoela","Maiara","Izabele","Gabrielly");

$con=count($nome)-1; 
//quantidade de linhas 1500
 for ($i = 0; $i <= 1500; $i++) {
	 
$count=rand ( 9 , $con ); //primeiro nome 
$countt=rand (9 , $con ) ; //segundo  nome
echo $nome[$count].",".$nome[$countt].",".$nome[$count].".".$nome[$countt]."@institutoidv.org,senha@DSD44AF,,/,,,,,,,,,,,,,,,,,,,,,";

echo"<br>";
}
?>
